parameters:
    omnipay.class: Janwebdev\OmnipayBundle\Manager\OmnipayManager

services:
    omnipay:
        class: "%omnipay.class%"
        arguments:
            - "@omnipay.factory"

    omnipay.factory:
        class: Omnipay\Common\GatewayFactory
        public: false